openapi: 3.1.0
info:
  title: Order Service Api
  description: Kitchen Order Service Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

paths:
  /v1/kitchen/orders:
    post:
      tags:
        - KitchenOrders
      summary: Get all kitchen orders with filter criteria
      description: Return all kitchen orders details with filter criteria
      operationId: getKitchenOrders
      requestBody:
        description: The search criteria
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KitchenOrderRequestDto'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KitchenOrderDto'

  /v1/kitchen/orders/{id}:
    get:
      tags:
        - KitchenOrders
      summary: Get kitchen order by id
      operationId: getKitchenOrderById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KitchenOrderDto'
        '404':
          description: Kitchen Order not found

components:
  schemas:

    KitchenOrderWriteDto:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        status:
          type: string
          enum: [ ACCEPTED, COOKING, COMPLETED ]
        items:
          type: array
          items:
            $ref: '#/components/schemas/KitchenOrderItemsWriteDto'

    KitchenOrderItemsWriteDto:
      type: object
      properties:
        itemName:
          type: string

    KitchenOrderDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        status:
          type: string
          enum: [ ACCEPTED, COOKING, COMPLETED ]
        items:
          type: array
          items:
            $ref: '#/components/schemas/KitchenOrderItemsDto'

    KitchenOrderItemsDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        kitchenOrderId:
          type: integer
          format: int64
        itemName:
          type: string
        cooked:
          type: boolean

    KitchenOrderRequestDto:
      description: Request dto provided in the request body to filter orders
      type: object
      properties:
        id:
          type: array
          description: Filter by kitchenOrderId
          nullable: true
          items:
            type: integer
            format: int64
        orderId:
          type: array
          description: Filter by orderId
          nullable: true
          items:
            type: integer
            format: int64
        status:
          type: array
          description: Filter by status
          nullable: true
          items:
            type: string
        items:
          type: array
          description: Filter by itemName
          nullable: true
          items:
            type: string